server:
  port: 9000
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/TransactionLog
    url: jdbc:mysql://localhost:4000/TransactionLog
    username: root
    driver-class-name: com.mysql.jdbc.Driver